### ISSUE TITLE
Error Requested format is not available. Use --list-formats for a list of available formats

### ISSUE THREAD

**Issue by sandrovasco** [m4heshd/ufc-ripper#8]
Download failed - "UFC Fight Night - Dariush x Tsarukyan"
UFCRError: ERROR: [generic] *~id=55dd51f7-5bfc-4d86-911d-46fa709c52a8~hmac=606d2c5b1aa86ec21ea59e473af64c0b3057de733cf67745e67770ed1b0c9562: Requested format is not available. Use --list-formats for a list of available formats

**Comment by m4heshd** [comment]
> URL: https://ufcfightpass.com.br/video/555202

Oh. Unfortunately, I cannot test stuff from Fight Pass Brazil since it requires an account for that specific region. 

But that same VOD works perfectly fine on the international version of the Fight Pass with the same settings as yours.

![image](https://github.com/m4heshd/ufc-ripper/assets/6711514/76f930a0-0359-45b2-aadd-9de8554c2780)


![image](https://github.com/m4heshd/ufc-ripper/assets/6711514/c4566b7d-caad-4a4b-b96a-dbca7f1dd3ae)

I'd suggest waiting a couple of hours and trying again because Fight Pass servers take eons to process live events into the rest of the available formats. Fight Pass Brazil version might be a little behind on the processing.

**Comment by sandrovasco** [comment]
I thought so, thank you for your attention and congratulations on the great work.

**Comment by m4heshd** [comment]
You're very welcome and the feedback is appreciated. Closing the issue.
